services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    ports:
      - "3002:3002"
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=3002
      - STORAGE_DIR=/app/storage
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./storage:/app/storage

volumes:
  redis-data:
